### ISSUE TITLE
경북 관련 학교 에러 

### ISSUE THREAD

**Issue by jaewon4492** [leegeunhyeok/node-school-kr#1]
Error: getaddrinfo ENOTFOUND stu.gbe.go.kr
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'stu.gbe.go.kr'
}

node-school-kr을 이용하여 경북관련 학교 급식을 가져올려고 하니 오류가 발생합니다.

stu.gbe.go.kr << 해당 사이트가 접속이 안되는 것 같은데 모듈문제인지 웹사이트 문제인지
잘 모르겠습니다.

**Comment by leegeunhyeok** [comment]
해당 문제 확인 결과, 기존의 [stu.gbe.go.kr](https://stu.gbe.go.kr) 주소가 [stu.gbe.kr](https://stu.gbe.go.kr)로 변경되었음을 확인했습니다.
